---
title: "Fire Project"
output: html_document
date: "2023-07-28"
---

---
title: "Fire Project"
output: html_document
date: "2023-07-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- read.csv("/cloud/project/FDdata.csv")

data_clean <- function(input_data){
  i <- 2
  output <- data[1,]
  while (i < length(input_data[,1])){
    curr_row <- input_data[i,]
  
    if (!(curr_row[,1] %in% output[,1])){
      if(!(curr_row$Department.Apparatus.Name %in% c("CH1", "CH2", "CH3", "CH4", "Battalion"))){
        if(isFALSE(curr_row$Apparatus.Was.Cancelled)){
          output <- rbind(output, curr_row)
        }
      }
    }
    i <- i + 1
  }
  return(output)
}
data <- data_clean(data)
write.csv(data, "fullFDdata.csv")
```

```{r}
origin_finder <- function(input_data){
  input_data$Response.station <- NaN
  
  for(i in 1:length(input_data[,1])){
    curr_row <- input_data[i,]
    if(curr_row$Station.. == "ST1" | curr_row$Department.Apparatus.Name == "Engine 8"
       | curr_row$Department.Apparatus.Name == "Rescue 1"){
      input_data[i,]$Response.station <- "ST1"
    }
    if(curr_row$Station.. == "ST2"){
      input_data[i,]$Response.station <- "ST2"
    }
    if(curr_row$Station.. == "ST3" | curr_row$Department.Apparatus.Name == "Engine 6"){
      input_data[i,]$Response.station <- "ST3"
    }
    if(curr_row$Station.. == "ST4"){
      input_data[i,]$Response.station <- "ST4"
    }
    if(curr_row$Station.. == "ST5"){
      input_data[i,]$Response.station <- "ST5"
    }
  }
  return(input_data)
}
data <- origin_finder(data)
data <- data[data$Response.station != "NaN",]
```

```{r}
ST1_1 <- data[data$Response.station == "ST1",][1:1000,]
ST1_1$tempKey <- c(1:1000)

ST1_2 <-data[data$Response.station == "ST1",][1001:1364,]
ST1_2$tempKey <- c(1:364)

ST2 <- data[data$Response.station == "ST2", ]
ST2$tempKey <- c(1:4)

ST3_1 <- data[data$Response.station == "ST3",][1:1000,]
ST3_1$tempKey <- c(1:1000)

ST3_2 <- data[data$Response.station == "ST3",][1001:1055,]
ST3_2$tempKey <- c(1:55)

ST4 <- data[data$Response.station == "ST4",]
ST4$tempKey <- c(1:3)
```

```{r}
ST1_1_times <- read.csv("/cloud/project/ST1_1_times.csv")
ST1_1_times <- ST1_1_times[, c("tempKey", "Total_TravelTime")]
ST1_1 <- merge(ST1_1, ST1_1_times, by="tempKey")

ST1_2_times <- read.csv("/cloud/project/ST1_2_times.csv")
ST1_2_times <- ST1_2_times[, c("tempKey", "Total_TravelTime")]
ST1_2 <- merge(ST1_2, ST1_2_times, by="tempKey")

ST2_times <- read.csv("/cloud/project/ST2_times.csv")
ST2_times <- ST2_times[, c("tempKey", "Total_TravelTime")]
ST2 <- merge(ST2, ST2_times, by="tempKey")

ST3_1_times <- read.csv("/cloud/project/ST3_1_times.csv")
ST3_1_times <- ST3_1_times[, c("tempKey", "Total_TravelTime")]
ST3_1 <- merge(ST3_1, ST3_1_times, by="tempKey")
 
ST3_2_times <- read.csv("/cloud/project/ST3_2_times.csv")
ST3_2_times <- ST3_2_times[, c("tempKey", "Total_TravelTime")]
ST3_2 <- merge(ST3_2, ST3_2_times, by="tempKey")

ST4_times <- read.csv("/cloud/project/ST4_times.csv")
ST4_times <- ST4_times[, c("tempKey", "Total_TravelTime")]
ST4 <- merge(ST4, ST4_times, by="tempKey")

data <- rbind(ST1_1, ST1_2, ST2, ST3_1, ST3_2, ST4)
data <- data[,-1]
```

```{r}
library(stringr)

add_time_date <- function(input_data){
  
  temp_df <-str_split_fixed(input_data$Alarm.Date.Time, " ", 2)
  dates <- str_split_fixed(temp_df[,1],"-", 3)
  dates[,1] <- paste(dates[,2], dates[,3], sep="")
  dates <- str_split_fixed(dates[,1]," ", 1)
  dates <- data.frame(as.numeric(sub(".", "", dates)))

  times <- str_split_fixed(temp_df[,2],":", 2)
  times[,1] <- paste(times[,1], times[,2], sep="")
  times <- data.frame(as.numeric(times[,1]))
  
  input_data$times <- times
  input_data$dates <- dates
  return(input_data)
}
data <- add_time_date(data)
```